### ISSUE TITLE
uk200705hostgraphweighted.txt 文件缺失

### ISSUE THREAD

**Issue by evilking-yh** [ariansacct/TrustRank#1]
您好，能提供一下 uk200705hostgraphweighted.txt 这个文件么，或者告知一下这个文件的数据格式是什么样的，如何生成？谢谢

**Comment by ariansacct** [comment]
Sure.

**Comment by evilking-yh** [comment]
thanks. My email is 1203004787@qq.com.

**Comment by vijaychandramanai** [comment]
can you please share uk200705hostgraphweighted.txt file to vijaychandra.manai@gmail.com

**Comment by bbinwang** [comment]
> Sure.

麻烦也发我一份，397264487@qq.com,多谢

**Comment by Czcong** [comment]
您好，可以也发一份uk200705hostgraphweighted.txt 给我吗？ 380241691@qq.com  谢谢啦

**Comment by ariansacct** [comment]
@evilking-yh @bbinwang @vijaychandramanai @Czcong sorry I couldn't find the exact file I had locally but I likely got it from https://law.di.unimi.it/webdata/uk-2007-05/ and https://chato.cl/webspam/datasets/uk2007/links/. You can use your own graphs as well.
This is a very old codebase for a research my lab was doing and I don't have the time or motivation to maintain it. It likely has bugs.
