### ISSUE TITLE
uk200705hostgraphweighted.txt

### ISSUE THREAD

**Issue by minangong** [ariansacct/TrustRank#2]
Hello, I'm sorry to disturb you. I download the uk-2007-05 dataset ,but the suffix of the file  is .graph . So, can you send me the  uk200705hostgraphweighted.txt . I will be grateful.                                                                                           ysc_mng@163.com

您好，很抱歉打扰到你，我下载了 uk-2007-05 数据集 ，但是后缀名是 .graph。并且不知如何转化。您能发我下uk200705hostgraphweighted.txt 文件吗，感谢                                                                                                  ysc_mng@163.com

**Comment by ariansacct** [comment]
Hi, I don't have this repo on my machine anymore. I suggest looking up the
original paper and you can probably find the input files. Also the file
extensions don't matter and as long as it's a text file you can read it the
same way or change the extension to whatever you want.

**Comment by ariansacct** [comment]
https://chato.cl/webspam/datasets/uk2007/links/
